### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by nathanmutin** [CurtinFRC/ModularVisionTracking#19]
Hi, I've cloned this project both on Windows and Ubuntu 18.04 but I can't manage to build it. Here are the build's outputs :
* [gradlew vision:build](https://gist.github.com/nathanmutin/89a9e9cafd5052806f9c0e162adbc65d)
* [gradlew vision:build --stacktrace](https://gist.github.com/nathanmutin/90c8682f0cd2cf8103accae712f459c5)

Maybe I'm doing it the wrong way, but it seems to me that I followed the instructions as well as I could. Thanks in advance for your help.

**Comment by CJBuchel** [comment]
Oh, sorry, i did not realise people would be trying to use it so soon. The Project is actually still incomplete, the issue you are probably having is vision map not being linked to anything and the threading not implemented which is your runnable issue, also i'm fairly certain the version of the code you are using doesn't have any processes. 
Currently this program is meant to be made for next years FRC game in 2020, so this is still being built steadily for then, and i can't really say when it will be fully completed.

 But if you are looking for some easy to use vision code to work with until then, the source for this project is still available and working, however it's not modular. 
I've just uploaded it now at (https://github.com/CJBuchel/Vision-Tracking-Format)
p.s sorry for the late reply, i only work on this project around once a week. And sometimes i don't see the issues page.

**Comment by nathanmutin** [comment]
No problem :) And thanks a lot for [the Vision-Tracking-Format project](https://github.com/CJBuchel/Vision-Tracking-Format), this is exactly what I was looking for.
